Futebol.UI/Controllers/JogadoresController.cs
using AutoMapper;
using Futebol.BLL;
using Futebol.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Futebol.UI.Controllers
{
    public class JogadoresController : Controller
    {
        JogadorLogic logic;

        public JogadoresController()
        {
            logic = new JogadorLogic();
        }

        public ActionResult Index()
        {
            var jogadores = logic.List();
            var jogadoresVM = Mapper.Map<List<Jogador>, List<JogadorVM>>(jogadores);

            return View(jogadoresVM);
        }

        public ActionResult Criar()
        {
            var jogadorVm = new JogadorVM
            {
                ListaTimes = ListaDeTimes(),
                ListaPosicoes = ListaDePosicoes()
            };

            return View(jogadorVm);
        }

        [HttpPost]
        public ActionResult Criar(JogadorVM jogadorVM)
        {
            return Salvar(jogadorVM);
        }

        public ActionResult Editar(int? id)
        {
            return Encontrar(id);
        }

        [HttpPost]
        public ActionResult Editar(JogadorVM jogadorVM)
        {
            return Salvar(jogadorVM);
        }

        public ActionResult Remover(int? id)
        {
            return Encontrar(id);
        }

        [HttpPost]
        public ActionResult Remover(int id)
        {
            try
            {
                logic.Remove(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return Encontrar(id);
            }
        }

        public ActionResult Detalhar(int? id)
        {
            return Encontrar(id);
        }

        private ActionResult Encontrar(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var jogador = logic.Find((int)id);
            var jogadorVM = Mapper.Map<Jogador, JogadorVM>(jogador);

            jogadorVM.ListaTimes = ListaDeTimes();
            jogadorVM.ListaPosicoes = ListaDePosicoes();

            return View(jogadorVM);
        }

        [HttpPost]
        private ActionResult Salvar(JogadorVM jogadorVM)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("O modelo não é válido.");

                var jogador = Mapper.Map<JogadorVM, Jogador>(jogadorVM);

                logic.Save(jogador);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);

                jogadorVM.ListaTimes = ListaDeTimes();
                jogadorVM.ListaPosicoes = ListaDePosicoes();

                return View(jogadorVM);
            }
        }

        public static SelectList ListaDeTimes()
        {
            var timeLogic = new TimeLogic();

            var times = timeLogic.List();

            return new SelectList(times, "TimeId", "Nome");
        }

        public static SelectList ListaDePosicoes()
        {
            var posicaoLogic = new PosicaoLogic();

            var posicoess = posicaoLogic.List();

            return new SelectList(posicoess, "PosicaoId", "Sigla");
        }
    }
}

Futebol.UI/Controllers/PosicoesController.cs
using AutoMapper;
using Futebol.BLL;
using Futebol.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Futebol.UI.Controllers
{
    public class PosicoesController : Controller
    {
        PosicaoLogic logic;

        public PosicoesController()
        {
            logic = new PosicaoLogic();
        }

        public ActionResult Index()
        {
            var posicoes = logic.List();
            var posicoesVM = Mapper.Map<List<Posicao>, List<PosicaoVM>>(posicoes);

            return View(posicoesVM);
        }

        public ActionResult Criar() => View();

        [HttpPost]
        public ActionResult Criar(PosicaoVM posicaoVM)
        {
            return Salvar(posicaoVM);
        }

        public ActionResult Editar(int? id)
        {
            return Encontrar(id);
        }

        [HttpPost]
        public ActionResult Editar(PosicaoVM posicaoVM)
        {
            return Salvar(posicaoVM);
        }

        public ActionResult Remover(int? id)
        {
            return Encontrar(id);
        }

        [HttpPost]
        public ActionResult Remover(int id)
        {
            try
            {
                logic.Remove(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return Encontrar(id);
            }
        }

        public ActionResult Detalhar(int? id)
        {
            return Encontrar(id);
        }

        private ActionResult Encontrar(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var posicao = logic.Find((int)id);
            var posicaoVM = Mapper.Map<Posicao, PosicaoVM>(posicao);

            return View(posicaoVM);
        }

        [HttpPost]
        private ActionResult Salvar(PosicaoVM posicaoVM)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("O modelo não é válido.");

                var posicao = Mapper.Map<PosicaoVM, Posicao>(posicaoVM);

                logic.Save(posicao);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(posicaoVM);
            }
        }
    }
}

Futebol.UI/Controllers/TimesController.cs
using AutoMapper;
using Futebol.BLL;
using Futebol.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Futebol.UI.Controllers
{
    public class TimesController : Controller
    {
        TimeLogic logic;

        public TimesController()
        {
            logic = new TimeLogic();
        }

        public ActionResult Index()
        {
            var times = logic.List();
            var timesVM = Mapper.Map<List<Time>, List<TimeVM>>(times);

            return View(timesVM);
        }

        public ActionResult Criar() => View();

        [HttpPost]
        public ActionResult Criar(TimeVM timeVM)
        {
            return Salvar(timeVM);
        }

        public ActionResult Editar(int? id)
        {
            return Encontrar(id);
        }

        [HttpPost]
        public ActionResult Editar(TimeVM timeVM)
        {
            return Salvar(timeVM);
        }

        public ActionResult Remover(int? id)
        {
            return Encontrar(id);
        }

        [HttpPost]
        public ActionResult Remover(int id)
        {
            try
            {
                logic.Remove(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return Encontrar(id);
            }
        }

        public ActionResult Detalhar(int? id)
        {
            return Encontrar(id);
        }

        private ActionResult Encontrar(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var time = logic.Find((int)id);
            var timeVM = Mapper.Map<Time, TimeVM>(time);

            return View(timeVM);
        }

        [HttpPost]
        private ActionResult Salvar(TimeVM timeVM)
        {
            try
            {
                if (!ModelState.IsValid)
                    throw new Exception("O modelo não é válido.");

                var time = Mapper.Map<TimeVM, Time>(timeVM);

                logic.Save(time);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(timeVM);
            }
        }
    }
}

Futebol.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Futebol</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-cosmo.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand"><i class="fa fa-soccer-ball-o"></i> Futebol</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Times")"><i class="fa fa-shield"></i> Times</a></li>
                    <li><a href="@Url.Action("Index", "Posicoes")"><i class="fa fa-list-ol"></i> Posições</a></li>
                    <li><a href="@Url.Action("Index", "Jogadores")"><i class="fa fa-user"></i> Jogadores</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Futebol</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>